In [1]:
from citylearn import  CityLearn
from pathlib import Path
from agent import Agent
import numpy as np

In [4]:
import os
os.getcwd()

'/Users/xiejiahan/PycharmProjects/RLinDR/CityLearn/scratch'

In [7]:
climate_zone = 5
params = {'data_path':
              Path("/Users/xiejiahan/PycharmProjects/RLinDR/CityLearn/data/Climate_Zone_"+
                   str(climate_zone)),
        'building_attributes':'building_attributes.json',
        'weather_file':'weather_data.csv',
        'solar_profile':'solar_generation_1kW.csv',
        'carbon_intensity':'carbon_intensity.csv',
        'building_ids':["Building_"+str(i) for i in [1,2,3,4,5,6,7,8,9]],
        'buildings_states_actions':'/Users/xiejiahan/PycharmProjects/RLinDR/CityLearn/buildings_state_action_space.json',
        'simulation_period': (0, 8760*4-1),
        'cost_function': ['ramping','1-load_factor','average_daily_peak','peak_demand','net_electricity_consumption','carbon_emissions'],
        'central_agent': False,
        'save_memory': False }

env = CityLearn(**params)
observations_spaces, actions_spaces = env.get_state_action_spaces()

In [11]:
obs = env.reset()
obs.__class__
obs.shape

(9,)

In [42]:
obs[0]

array([  1.       ,   8.       ,   1.       ,   9.4      ,  10.02     ,
        16.21     ,  14.15     ,  94.12     ,  91.12     ,  82.93     ,
        91.65     ,   0.       ,  -0.       , 170.84     ,   0.       ,
         0.       ,  -0.       ,   5.32     ,   0.       ,  18.93     ,
        77.92     ,   9.8      ,   0.       ,   0.       ,   0.       ,
         0.       ,   9.8      ,   0.5262901], dtype=float32)

In [30]:
obs_n = np.array([[1,2,3],
                  [4,5,6]])
ret = [np.vstack(obs_n[:,i]) for i in range(3)]
len(ret)

3

In [6]:
import torch
import numpy as np

In [3]:
actions = torch.tensor([[1,3,2],[6,4,5]])
int_acs = actions.max(dim=1,keepdims=True)[1]
int_acs

tensor([[1],
        [0]])

In [6]:
all_q = torch.tensor([[5,2,1],[4,3,2]])
q = all_q.gather(1, int_acs)
q

tensor([[2],
        [4]])

In [5]:
arr = np.arange(0, 8760*4)
arr[-8760:]

array([26280, 26281, 26282, ..., 35037, 35038, 35039])

In [ ]:
torch.tensor([0.0], device=)